/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Analista;
import Modelo.Empleado;
import Controlador.MyList;
import Modelo.Esueldomaximo;
import Modelo.Programador;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import static java.lang.Math.random;
import java.util.Calendar;
import static java.util.Calendar.DAY_OF_MONTH;
import static java.util.Calendar.MONTH;
import static java.util.Calendar.YEAR;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    MyList Lista;
    boolean programador=false;
    
    public Vista() {
        initComponents();
        Lista = new MyList();
        Empleado emp1 =new Programador(2,"Pablo",2000,3000,2023,11,10,200,true);
        Empleado emp2 =new Analista(1,"Alba",2000,3000,2023,11,10,20,20);
        Empleado emp3 =new Programador(3,"Abel",2000,3000,2023,11,10,200,true);
        Lista.add(emp1);
        Lista.add(emp2);
        Lista.add(emp3);
        inicio(Lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void inicio(MyList Lista){
        Empleado aux = (Empleado) Lista.getActual().getMain();
        txtnumero.setEditable(false);
        txtnombre.setEditable(false);
        txtsueldo.setEditable(false);
        txtsueldom.setEditable(false);
        txtfecha.setEditable(false);
        txtatributo1.setEditable(false);
        txtatributo2.setEditable(false);
        
        txtnumero.setText(""+aux.getNumero());
        txtnombre.setText(""+aux.getNombre());
        txtsueldo.setText(""+aux.getSueldo());
        txtsueldom.setText(""+aux.getSueldomax());
        txtfecha.setText(""+(aux.getFecha()).get(DAY_OF_MONTH)+"/"+(aux.getFecha()).get(MONTH)+"/"+(aux.getFecha()).get(YEAR));
        if(aux instanceof Programador){
            lbatributo1.setText("Sueldo Extra");
            txtatributo1.setText(""+((Programador)aux).getSueldoextra());
            lbatributo2.setText("Es senior?(true/false)");
            txtatributo2.setText(""+((Programador)aux).isSenior());
        }
        if(aux instanceof Analista){
            lbatributo1.setText("Plus Anual");
            txtatributo1.setText(""+((Analista)aux).getPlus_anual());
            lbatributo2.setText("Edad");
            txtatributo2.setText(""+((Analista)aux).getEdad());
        }
        btconfirmar.setEnabled(false);
        btcancelar.setEnabled(false);
        
            if(aux instanceof Programador){
                
            
                if(((Programador)aux).cumplemes()){
                btcalcula.setEnabled(true);
                }else{
                btcalcula.setEnabled(false);
                }
            }else{
                if(((Analista)aux).cumpleaño()){
                btcalcula.setEnabled(true);
                }else{
                btcalcula.setEnabled(false);
                }
            }
    }
    
    public void crear(){
        txtnumero.setText("");
        txtnombre.setText("");
        txtsueldo.setText("");
        txtsueldom.setText("");
        txtfecha.setText("");
        txtatributo1.setText("");
        txtatributo2.setText("");
        btconfirmar.setEnabled(true);
        btcancelar.setEnabled(true);
        btsiguiente.setEnabled(false);
        btanterior.setEnabled(false);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbnumero = new javax.swing.JLabel();
        lbnombre = new javax.swing.JLabel();
        lbsueldo = new javax.swing.JLabel();
        lbsueldom = new javax.swing.JLabel();
        lbfecha = new javax.swing.JLabel();
        lbatributo1 = new javax.swing.JLabel();
        lbatributo2 = new javax.swing.JLabel();
        txtatributo2 = new javax.swing.JTextField();
        txtatributo1 = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        txtsueldom = new javax.swing.JTextField();
        txtsueldo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        btsiguiente = new javax.swing.JButton();
        btanterior = new javax.swing.JButton();
        btmasivo = new javax.swing.JButton();
        btprogramador = new javax.swing.JButton();
        btanalista = new javax.swing.JButton();
        btconfirmar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btultimo = new javax.swing.JButton();
        btprimero = new javax.swing.JButton();
        btcargar = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        btordenar = new javax.swing.JButton();
        btcalcula = new javax.swing.JButton();
        btlista = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbnumero.setText("Numero");

        lbnombre.setText("Nombre");

        lbsueldo.setText("Sueldo");

        lbsueldom.setText("Sueldo Max");

        lbfecha.setText("Fecha");

        lbatributo1.setText("lbatributo1");

        lbatributo2.setText("lbatributo2");

        txtatributo2.setText("jTextField1");

        txtatributo1.setText("jTextField1");

        txtfecha.setText("jTextField1");

        txtsueldom.setText("jTextField1");

        txtsueldo.setText("jTextField1");

        txtnombre.setText("jTextField1");

        txtnumero.setText("jTextField1");
        txtnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroActionPerformed(evt);
            }
        });

        btsiguiente.setText("Siguiente");
        btsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsiguienteActionPerformed(evt);
            }
        });

        btanterior.setText("Anterior");
        btanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanteriorActionPerformed(evt);
            }
        });

        btmasivo.setText("Creado masivo");
        btmasivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmasivoActionPerformed(evt);
            }
        });

        btprogramador.setText("Añadir Programador");
        btprogramador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprogramadorActionPerformed(evt);
            }
        });

        btanalista.setText("Añadir Analista");
        btanalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanalistaActionPerformed(evt);
            }
        });

        btconfirmar.setText("Confirmar");
        btconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconfirmarActionPerformed(evt);
            }
        });

        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        btultimo.setText("Ultimo");
        btultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btultimoActionPerformed(evt);
            }
        });

        btprimero.setText("Primero");
        btprimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprimeroActionPerformed(evt);
            }
        });

        btcargar.setText("Cargar Datos");
        btcargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcargarActionPerformed(evt);
            }
        });

        btguardar.setText("Guardar datos");
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });

        btordenar.setText("Ordenar lista");
        btordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btordenarActionPerformed(evt);
            }
        });

        btcalcula.setText("calcular");
        btcalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcalculaActionPerformed(evt);
            }
        });

        btlista.setText("Lista");
        btlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbatributo1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbatributo2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbsueldom, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsueldom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtatributo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtatributo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btanterior)
                        .addGap(57, 57, 57)
                        .addComponent(btmasivo)
                        .addGap(54, 54, 54)
                        .addComponent(btsiguiente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btprimero)
                                .addGap(11, 11, 11)
                                .addComponent(btprogramador)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btcargar))
                                    .addComponent(btcancelar))
                                .addGap(42, 42, 42)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btconfirmar))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btguardar)
                                    .addComponent(btanalista))
                                .addGap(34, 34, 34)
                                .addComponent(btultimo)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btcalcula)
                .addGap(46, 46, 46)
                .addComponent(btordenar)
                .addGap(55, 55, 55)
                .addComponent(btlista)
                .addGap(63, 63, 63))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbatributo1, lbatributo2, lbfecha, lbnombre, lbnumero, lbsueldo, lbsueldom});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtatributo1, txtatributo2, txtfecha, txtnombre, txtnumero, txtsueldo, txtsueldom});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbnumero))
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbsueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsueldom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbsueldom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtatributo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbatributo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtatributo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbatributo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btanterior)
                    .addComponent(btmasivo))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btprogramador)
                    .addComponent(btanalista)
                    .addComponent(btultimo)
                    .addComponent(btprimero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btconfirmar)
                    .addComponent(btcancelar))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btguardar)
                    .addComponent(btcargar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btordenar)
                    .addComponent(btcalcula)
                    .addComponent(btlista))
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroActionPerformed
        
    }//GEN-LAST:event_txtnumeroActionPerformed

    private void btanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanteriorActionPerformed
        if(!Lista.esprimero()){
            btsiguiente.setEnabled(true);
            btanterior.setEnabled(true);
            Lista.anterior();
            inicio(Lista);
        }else{
            btsiguiente.setEnabled(true);
            btanterior.setEnabled(false);
            Lista.anterior();
            inicio(Lista);
        }
    }//GEN-LAST:event_btanteriorActionPerformed

    private void btsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsiguienteActionPerformed
        if(!Lista.esultimo()){
            btsiguiente.setEnabled(true);
            btanterior.setEnabled(true);
            Lista.siguiente();
            inicio(Lista);
            Empleado x = (Empleado)Lista.getActual().getMain();
            if(x instanceof Programador){
                
            
                if(((Programador)x).cumplemes()){
                btcalcula.setEnabled(true);
                }else{
                btcalcula.setEnabled(false);
                }
            }else{
                if(((Analista)x).cumpleaño()){
                btcalcula.setEnabled(true);
                }else{
                btcalcula.setEnabled(false);
                }
            }
        }else{
            btsiguiente.setEnabled(false);
            btanterior.setEnabled(true);
            Lista.siguiente();
            inicio(Lista);
        }
        
    }//GEN-LAST:event_btsiguienteActionPerformed

    private void btmasivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmasivoActionPerformed
        Random random = new Random();
        for(int i=0;i<100000;i++){
            Empleado aux = new Programador(random.nextInt(98000)+2000,null,0,0,0,0,0,0,true);
            Lista.add(aux);
        }
        for(int i=0;i<20;i++){
            Empleado aux = new Analista(random.nextInt(2000),null,0,0,0,0,0,0,0);
            Lista.add(aux);
        }
    }//GEN-LAST:event_btmasivoActionPerformed

    private void btprogramadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprogramadorActionPerformed
        crear();
        txtnumero.setEditable(true);
        txtnombre.setEditable(true);
        txtsueldo.setEditable(true);
        txtsueldom.setEditable(true);
        txtatributo1.setEditable(true);
        txtatributo2.setEditable(true);
        lbatributo1.setText("Sueldo Extra");
        lbatributo2.setText("Es senior?(true/false)");
        programador=true;
    }//GEN-LAST:event_btprogramadorActionPerformed

    private void btconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconfirmarActionPerformed
        
            String num=txtnumero.getText();
            String nom=txtnombre.getText();
            String sue=txtsueldo.getText();
            String suem=txtsueldom.getText();
            String atrib1=txtatributo1.getText();
            String atrib2=txtatributo2.getText();
            int nume = Integer.parseInt(num);
            int sueld = Integer.parseInt(sue);
            int sueldm = Integer.parseInt(suem);
            int d= Calendar.DAY_OF_MONTH;
            int m= Calendar.MONTH;
            int a= Calendar.YEAR;
            if(programador == true){
                int sueldextra = Integer.parseInt(atrib1);
                boolean senior = Boolean.parseBoolean(atrib2);
                Empleado nuevo = new Programador(nume,nom,sueld,sueldm,d,m,a,sueldextra,senior);
                Lista.add(nuevo);
                inicio(Lista);
                programador=false;
            }else{
                int plus = Integer.parseInt(atrib1);
                int edad = Integer.parseInt(atrib2);
                Empleado nuevo = new Analista(nume,nom,sueld,sueldm,d,m,a,plus,edad);
                Lista.add(nuevo);
                inicio(Lista);
            }
        btsiguiente.setEnabled(true);
        btanterior.setEnabled(true);
        
    }//GEN-LAST:event_btconfirmarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        inicio(Lista);
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btanalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanalistaActionPerformed
        crear();
        txtnumero.setEditable(true);
        txtnombre.setEditable(true);
        txtsueldo.setEditable(true);
        txtsueldom.setEditable(true);
        txtatributo1.setEditable(true);
        txtatributo2.setEditable(true);
        lbatributo1.setText("Plus anual");
        lbatributo2.setText("Edad");
    }//GEN-LAST:event_btanalistaActionPerformed

    private void btprimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprimeroActionPerformed
        Lista.setActual(Lista.getFirstNode());
        inicio(Lista);
    }//GEN-LAST:event_btprimeroActionPerformed

    private void btultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btultimoActionPerformed
        Lista.setActual(Lista.getLastNode());
        inicio(Lista);
    }//GEN-LAST:event_btultimoActionPerformed

    private void btordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btordenarActionPerformed
        long totalSum=0;
        long startTime = System.currentTimeMillis();

            Lista.sort();
            inicio(Lista);

        totalSum+= (System.currentTimeMillis()-startTime);
        JOptionPane.showMessageDialog(rootPane, "Tiempo en ordenar: " + totalSum + " milisegundos.");
        System.out.println("Tiempo en ordenar: " + totalSum + " milisegundos.");
        
    }//GEN-LAST:event_btordenarActionPerformed

    private void btcalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcalculaActionPerformed
        Empleado x = (Empleado)Lista.getActual().getMain();
        if(x instanceof Programador){
            float sueldo = Float.parseFloat(txtsueldo.getText());
            int sueldom = Integer.parseInt(txtsueldom.getText());
            int plus = Integer.parseInt(txtatributo1.getText());
            float nuevosuel = sueldo+plus;
            Empleado actual = (Empleado)Lista.getActual().getMain();
            try {
                actual.setSueldo(nuevosuel);
            } catch (Esueldomaximo ex) {
                Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            float sueldo = Float.parseFloat(txtsueldo.getText());
            int sueldom = Integer.parseInt(txtsueldom.getText());
            int porcentaje = Integer.parseInt(txtatributo1.getText());
            float nuevosuel = ((sueldo*porcentaje)/100)+sueldo;
            Empleado actual = (Empleado)Lista.getActual().getMain();
            try {
                actual.setSueldo(nuevosuel);
            } catch (Esueldomaximo ex) {
                Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        inicio(Lista);
        btcalcula.setEnabled(false);
        
        
    }//GEN-LAST:event_btcalculaActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        Lista.guardar();
    }//GEN-LAST:event_btguardarActionPerformed

    private void btcargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcargarActionPerformed
        try {
            FileInputStream fichsalida = new FileInputStream("Lista.ser");
            ObjectInputStream recorredor = new ObjectInputStream(fichsalida);
            
            while(true){
                try{
                Lista.add((Empleado)recorredor.readObject());
                }catch(IOException e){
                    break;
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
        inicio(Lista);
    }//GEN-LAST:event_btcargarActionPerformed

    private void btlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlistaActionPerformed
        Lista.CrearJList();
    }//GEN-LAST:event_btlistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btanalista;
    private javax.swing.JButton btanterior;
    private javax.swing.JButton btcalcula;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btcargar;
    private javax.swing.JButton btconfirmar;
    private javax.swing.JButton btguardar;
    private javax.swing.JButton btlista;
    private javax.swing.JButton btmasivo;
    private javax.swing.JButton btordenar;
    private javax.swing.JButton btprimero;
    private javax.swing.JButton btprogramador;
    private javax.swing.JButton btsiguiente;
    private javax.swing.JButton btultimo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbatributo1;
    private javax.swing.JLabel lbatributo2;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbnumero;
    private javax.swing.JLabel lbsueldo;
    private javax.swing.JLabel lbsueldom;
    private javax.swing.JTextField txtatributo1;
    private javax.swing.JTextField txtatributo2;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JTextField txtsueldom;
    // End of variables declaration//GEN-END:variables
}
