
package Vista;
import Modelo.Empresa;
import Modelo.Empresario;
import Vista.JPanelEntrar;

public final class JFramePrincipal extends javax.swing.JFrame {

    Empresa E = new Empresa();
    JPanelAcercade panelAcercade = new JPanelAcercade();
    JPanelPerfil panelPerfil = new JPanelPerfil();
    JPanelUnaaUna panelfila;
    JPanelTabla panelTabla = new JPanelTabla();
    JPanelEntrar panelEntrar = new JPanelEntrar(this,E);
    
    public JFramePrincipal() {
        initComponents();
        mostrarmenu(false);
        cambiarPanel(panelEntrar);
    }
    
    public void cambiarPanel(javax.swing.JPanel panel) {
        this.setContentPane(panel);
        this.pack();
    }
    
    public void mostrarmenu(boolean x){
        MenuVisualizar.setVisible(x);
        MenuAcercade.setVisible(x);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuValidar = new javax.swing.JMenu();
        ItemIniciarSesion = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();
        MenuVisualizar = new javax.swing.JMenu();
        ItemUnaaUNa = new javax.swing.JMenuItem();
        ItemJTable = new javax.swing.JMenuItem();
        ItemPerfil = new javax.swing.JMenuItem();
        MenuAcercade = new javax.swing.JMenu();
        ItemAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuValidar.setText("Validar");

        ItemIniciarSesion.setText("Iniciar Sesion");
        ItemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemIniciarSesionActionPerformed(evt);
            }
        });
        MenuValidar.add(ItemIniciarSesion);

        ItemSalir.setText("Salir");
        ItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSalirActionPerformed(evt);
            }
        });
        MenuValidar.add(ItemSalir);

        jMenuBar1.add(MenuValidar);

        MenuVisualizar.setText("Visualizar");

        ItemUnaaUNa.setText("Ver filas una a una");
        ItemUnaaUNa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemUnaaUNaActionPerformed(evt);
            }
        });
        MenuVisualizar.add(ItemUnaaUNa);

        ItemJTable.setText("Ver filas en un JTable");
        ItemJTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemJTableActionPerformed(evt);
            }
        });
        MenuVisualizar.add(ItemJTable);

        ItemPerfil.setText("Ver perfil");
        ItemPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemPerfilActionPerformed(evt);
            }
        });
        MenuVisualizar.add(ItemPerfil);

        jMenuBar1.add(MenuVisualizar);

        MenuAcercade.setText("Acerca de");

        ItemAcercade.setText("Acerca de");
        ItemAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAcercadeActionPerformed(evt);
            }
        });
        MenuAcercade.add(ItemAcercade);

        jMenuBar1.add(MenuAcercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemIniciarSesionActionPerformed
        this.cambiarPanel(panelEntrar);
    }//GEN-LAST:event_ItemIniciarSesionActionPerformed

    private void ItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSalirActionPerformed
        mostrarmenu(false);
    }//GEN-LAST:event_ItemSalirActionPerformed

    private void ItemUnaaUNaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUnaaUNaActionPerformed
        panelfila = new JPanelUnaaUna(E);
        this.cambiarPanel(panelfila);
    }//GEN-LAST:event_ItemUnaaUNaActionPerformed

    private void ItemAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAcercadeActionPerformed
        this.cambiarPanel(panelAcercade);
    }//GEN-LAST:event_ItemAcercadeActionPerformed

    private void ItemJTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemJTableActionPerformed
        this.cambiarPanel(panelTabla);
    }//GEN-LAST:event_ItemJTableActionPerformed

    private void ItemPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemPerfilActionPerformed
        this.cambiarPanel(panelPerfil);
    }//GEN-LAST:event_ItemPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAcercade;
    private javax.swing.JMenuItem ItemIniciarSesion;
    private javax.swing.JMenuItem ItemJTable;
    private javax.swing.JMenuItem ItemPerfil;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JMenuItem ItemUnaaUNa;
    private javax.swing.JMenu MenuAcercade;
    private javax.swing.JMenu MenuValidar;
    private javax.swing.JMenu MenuVisualizar;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
